version: '3.9'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - api
  api:
    build: ./backend/api
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis
      - S3_ENDPOINT=http://minio:9000
      - AWS_ACCESS_KEY_ID=minio
      - AWS_SECRET_ACCESS_KEY=minio123
    depends_on:
      - redis
      - minio
  worker:
    build: ./backend/worker
    environment:
      - REDIS_HOST=redis
      - S3_ENDPOINT=http://minio:9000
      - AWS_ACCESS_KEY_ID=minio
      - AWS_SECRET_ACCESS_KEY=minio123
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    depends_on:
      - redis
      - minio
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  minio:
    image: minio/minio:latest
    command: server /data --console-address :9001
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
volumes:
  minio-data:
